# Author: Christopher Limawan
# File: Dockerfile.development
# Purpose: Docker compose configuration for development environment, adjusted for Tyeso web 

version: "3.9"

services: 
  frontend:
    container_name: tyeso-web_frontend
    build: 
      dockerfile: Dockerfile.development
      context: .
    restart: always #change if you don't want your container restarting
    ports:
      - 3000:3000
    env_file:
      - .env.development
    volumes:
      - .:/app

networks:
  default:
    name: dev_tyeso-network_default
    driver: bridge