import { ProductCard } from "../model/productCard";

export const hotProduct: ProductCard[] = [
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Stainless Steel Travel Tumbler",
    productDiscount: true,
    productPrice: 1200000,
    originalProductPrice: 1500000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Insulated Coffee Mug",
    productDiscount: false,
    productPrice: 2500000,
    originalProductPrice: 3000000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Eco-Friendly Bamboo Tumbler",
    productDiscount: true,
    productPrice: 800000,
    originalProductPrice: 1000000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Ceramic Travel Cup",
    productDiscount: false,
    productPrice: 1500000,
    originalProductPrice: 1700000,
  },
  {
    productId: "5",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Stainless Steel Travel Tumbler",
    productDiscount: true,
    productPrice: 1200000,
    originalProductPrice: 1500000,
  },
  {
    productId: "6",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Insulated Coffee Mug",
    productDiscount: false,
    productPrice: 2500000,
    originalProductPrice: 3000000,
  },
  {
    productId: "7",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Eco-Friendly Bamboo Tumbler",
    productDiscount: true,
    productPrice: 800000,
    originalProductPrice: 1000000,
  },
  {
    productId: "8",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Ceramic Travel Cup",
    productDiscount: false,
    productPrice: 1500000,
    originalProductPrice: 1700000,
  },
];

export const newArrivalProduct: ProductCard[] = [
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Double-Wall Vacuum Tumbler",
    productDiscount: true,
    productPrice: 1800000,
    originalProductPrice: 2200000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Large Ceramic Mug",
    productDiscount: false,
    productPrice: 2000000,
    originalProductPrice: 2500000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Stainless Steel Insulated Cup",
    productDiscount: true,
    productPrice: 3000000,
    originalProductPrice: 3500000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Reusable Plastic Tumbler",
    productDiscount: false,
    productPrice: 1400000,
    originalProductPrice: 1600000,
  },
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Compact Travel Tumbler",
    productDiscount: true,
    productPrice: 1300000,
    originalProductPrice: 1800000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Insulated Sipping Cup",
    productDiscount: true,
    productPrice: 900000,
    originalProductPrice: 1300000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Large Coffee Tumbler",
    productDiscount: true,
    productPrice: 2400000,
    originalProductPrice: 3000000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Precision Drinking Cup",
    productDiscount: true,
    productPrice: 1600000,
    originalProductPrice: 2000000,
  }
];

export const trendingProduct: ProductCard[] = [
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Premium Glass Tumbler Set",
    productDiscount: true,
    productPrice: 2300000,
    originalProductPrice: 2700000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Smart Temperature Display Mug",
    productDiscount: false,
    productPrice: 1250000,
    originalProductPrice: 1400000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Classic Ceramic Tea Cup",
    productDiscount: true,
    productPrice: 850000,
    originalProductPrice: 1000000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Portable Insulated Tumbler",
    productDiscount: true,
    productPrice: 1900000,
    originalProductPrice: 2200000,
  },
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Compact Travel Tumbler",
    productDiscount: true,
    productPrice: 1300000,
    originalProductPrice: 1800000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Insulated Sipping Cup",
    productDiscount: true,
    productPrice: 900000,
    originalProductPrice: 1300000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Large Coffee Tumbler",
    productDiscount: true,
    productPrice: 2400000,
    originalProductPrice: 3000000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Precision Drinking Cup",
    productDiscount: true,
    productPrice: 1600000,
    originalProductPrice: 2000000,
  }
];

export const onSaleProduct: ProductCard[] = [
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Compact Travel Tumbler",
    productDiscount: true,
    productPrice: 1300000,
    originalProductPrice: 1800000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Insulated Sipping Cup",
    productDiscount: true,
    productPrice: 900000,
    originalProductPrice: 1300000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Large Coffee Tumbler",
    productDiscount: true,
    productPrice: 2400000,
    originalProductPrice: 3000000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Precision Drinking Cup",
    productDiscount: true,
    productPrice: 1600000,
    originalProductPrice: 2000000,
  },
  {
    productId: "1",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Compact Travel Tumbler",
    productDiscount: true,
    productPrice: 1300000,
    originalProductPrice: 1800000,
  },
  {
    productId: "2",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Insulated Sipping Cup",
    productDiscount: true,
    productPrice: 900000,
    originalProductPrice: 1300000,
  },
  {
    productId: "3",
    productImage: "/a.jpg",
    productRating: 5,
    productName: "Large Coffee Tumbler",
    productDiscount: true,
    productPrice: 2400000,
    originalProductPrice: 3000000,
  },
  {
    productId: "4",
    productImage: "/a.jpg",
    productRating: 4,
    productName: "Precision Drinking Cup",
    productDiscount: true,
    productPrice: 1600000,
    originalProductPrice: 2000000,
  }
];
