import { ProductCard } from "../model/product";

export const hotProduct: ProductCard[] = [
  {
    product_id: "1",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Maximus Power Drill",
    discount: true,
    price: 1200000,
    original_price: 1500000,
  },
  {
    product_id: "2",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Titanium Wrench Set",
    discount: false,
    price: 2500000,
    original_price: 3000000,
  },
  {
    product_id: "3",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Pro Tech Hammer",
    discount: true,
    price: 800000,
    original_price: 1000000,
  },
  {
    product_id: "4",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Ultimate Screwdriver Kit",
    discount: false,
    price: 1500000,
    original_price: 1700000,
  },
  {
    product_id: "5",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Maximus Power Drill",
    discount: true,
    price: 1200000,
    original_price: 1500000,
  },
  {
    product_id: "6",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Titanium Wrench Set",
    discount: false,
    price: 2500000,
    original_price: 3000000,
  },
  {
    product_id: "7",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Pro Tech Hammer",
    discount: true,
    price: 800000,
    original_price: 1000000,
  },
  {
    product_id: "8",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Ultimate Screwdriver Kit",
    discount: false,
    price: 1500000,
    original_price: 1700000,
  },
];

export const newArrivalProduct: ProductCard[] = [
  {
    product_id: "1",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Speedy Electric Drill",
    discount: true,
    price: 1800000,
    original_price: 2200000,
  },
  {
    product_id: "2",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Heavy Duty Saw",
    discount: false,
    price: 2000000,
    original_price: 2500000,
  },
  {
    product_id: "3",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Cordless Grinder",
    discount: true,
    price: 3000000,
    original_price: 3500000,
  },
  {
    product_id: "4",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Precision Cutter",
    discount: false,
    price: 1400000,
    original_price: 1600000,
  },
];

export const trendingProduct: ProductCard[] = [
  {
    product_id: "1",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "All-in-One Toolkit",
    discount: true,
    price: 2300000,
    original_price: 2700000,
  },
  {
    product_id: "2",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Smart Laser Measure",
    discount: false,
    price: 1250000,
    original_price: 1400000,
  },
  {
    product_id: "3",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Advanced Screwdriver Set",
    discount: true,
    price: 850000,
    original_price: 1000000,
  },
  {
    product_id: "4",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Powerful Sander",
    discount: true,
    price: 1900000,
    original_price: 2200000,
  },
];

export const onSaleProduct: ProductCard[] = [
  {
    product_id: "1",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Compact Drill Machine",
    discount: true,
    price: 1300000,
    original_price: 1800000,
  },
  {
    product_id: "2",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Pro Sander",
    discount: true,
    price: 900000,
    original_price: 1300000,
  },
  {
    product_id: "3",
    photo_link: "/a.jpg",
    rating: 5,
    product_name: "Industrial Grinder",
    discount: true,
    price: 2400000,
    original_price: 3000000,
  },
  {
    product_id: "4",
    photo_link: "/a.jpg",
    rating: 4,
    product_name: "Precision Drill Set",
    discount: true,
    price: 1600000,
    original_price: 2000000,
  },
];
